p8105\_mtp\_hx2263
================
Tiffany Xi
10/16/2018

### Load dataset

Import the data file with `read_csv` using relative path.

``` r
am_data = 
  read_csv(file = "./data/p8105_mtp_data.csv")
```

### Tidy data

Use `fct_relevel` to reorder the weekdays to normal order and change `day` into factors; Then `gather` takes all `activity.*` columns and collapses into key-value pairs, duplicating all other columns as needed.

``` r
am_data_tidy = 
  am_data %>% 
  janitor::clean_names() %>% 
  mutate(day = fct_relevel(day, str_c(c("Sunday", "Monday", "Tuesday", "Wednesday",
                                        "Thursday", "Friday", "Saturday"))))%>%
  gather(key = "activity", value = "act_counts", activity_1:activity_1440) %>% 
  separate(activity, into = c("act", "time"), sep = "_") %>% 
  select(-act) %>% 
  arrange(week, day) %>% 
  mutate(time = as.integer(time),
         act_counts = as.numeric(act_counts))

skimr::skim(am_data_tidy)
```

    ## Skim summary statistics
    ##  n obs: 473760 
    ##  n variables: 4 
    ## 
    ## ── Variable type:factor ───────────────────────────────────────────────────────────────────────────
    ##  variable missing complete      n n_unique
    ##       day       0   473760 473760        7
    ##                                      top_counts ordered
    ##  Sun: 67680, Mon: 67680, Tue: 67680, Wed: 67680   FALSE
    ## 
    ## ── Variable type:integer ──────────────────────────────────────────────────────────────────────────
    ##  variable missing complete      n  mean     sd p0    p25   p50     p75
    ##      time       0   473760 473760 720.5 415.69  1 360.75 720.5 1080.25
    ##      week       0   473760 473760  24    13.56  1  12     24     36   
    ##  p100     hist
    ##  1440 ▇▇▇▇▇▇▇▇
    ##    47 ▇▇▇▇▇▇▇▇
    ## 
    ## ── Variable type:numeric ──────────────────────────────────────────────────────────────────────────
    ##    variable missing complete      n   mean     sd p0 p25 p50 p75  p100
    ##  act_counts       0   473760 473760 240.34 415.53  1   1  43 335 10417
    ##      hist
    ##  ▇▁▁▁▁▁▁▁

### Describe the resulting dataset

This original dataset has 1442 columns and 329 rows, which means there are 329 observations and 1442 variables in raw data. Resulting dataset contains 473760 observations and 4 variables which represents the record of 473760 minutes in 329 days of 47 weeks. Variables `week`, `day`, `activity.*` respectively stand for the week number, weekdays in that week, and the activity counts for each minute of a 24-hour day starting at midnight. In tidy dataset, `time` is the minute count in one specific day and `act_counts` is the same as `activity.*`.

Discuss any additional exploratory analyses you conduct, but only include results you think are interesting

``` r
am_data_tidy %>% 
  group_by(time) %>% 
  summarise(mean_act_counts = mean(act_counts)) %>% 
  ggplot(aes(x = time, y = mean_act_counts)) + 
  geom_line() +
  theme_bw()
```

![](p8105_mtp_hx2263_files/figure-markdown_github/unnamed-chunk-1-1.png)

``` r
am_data_tidy %>% 
  group_by(week) %>% 
  summarise(total_week = sum(act_counts)) %>% 
  ggplot(aes(x = week, y = total_week)) +
  geom_line() +
  geom_smooth() +
  theme_bw()+ 
  labs(
    title = "Weekly plot",
    x = "Week",
    y = "Total activity counts in that week",
    caption = "Data from p8105_mtp_data"
  ) +
  scale_x_continuous(breaks = c(0, 3, 5, 10, 12, 15, 20, 25, 30, 35, 40, 45, 47))
```

    ## `geom_smooth()` using method = 'loess' and formula 'y ~ x'

![](p8105_mtp_hx2263_files/figure-markdown_github/unnamed-chunk-2-1.png)

The total activeness of the week of this patient increased in the last 47 weeks, although there were many moderate fluctuations over time period, the overall trend is upwards. There are a huge drop in 3rd week and 12nd week, which could due to the weak phyisical condition or depression mentally to cause the inactivity. But the data in third week is a little odd it could because the patient took off the device some time in week 3.

visually inspect distributions for outliers, but include only if these are informative

``` r
summary(am_data_tidy$act_counts)
```

    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##     1.0     1.0    43.0   240.3   335.0 10417.0

``` r
am_data_tidy_1 = am_data_tidy %>% 
  filter(act_counts > 1)
1.5*(summary(am_data_tidy_1$act_counts)[5]-summary(am_data_tidy_1$act_counts)[2])+summary(am_data_tidy_1$act_counts)[5]
```

    ## 3rd Qu. 
    ##    1355

``` r
am_data_tidy %>% 
  filter(act_counts > 1355) %>% 
  mutate(id = as.integer(rownames(.))) %>% 
  ggplot(aes(x = act_counts)) +
  geom_density()
```

![](p8105_mtp_hx2263_files/figure-markdown_github/unnamed-chunk-3-1.png)

``` r
am_data_tidy %>% 
  filter(act_counts > 1) %>% 
  mutate(inde = as.integer(rownames(.))) %>% 
  ggplot(aes(x = inde, y = act_counts)) +
  geom_boxplot()
```

    ## Warning: Continuous x aesthetic -- did you forget aes(group=...)?

![](p8105_mtp_hx2263_files/figure-markdown_github/unnamed-chunk-4-1.png)

``` r
am_data_tidy %>% 
  group_by(week, day) %>% 
  ggplot(aes(x = time, y = act_counts, color = week)) +
  facet_grid( ~ day) +
  geom_line(alpha = .4)
```

![](p8105_mtp_hx2263_files/figure-markdown_github/unnamed-chunk-5-1.png)

``` r
am_data_tidy %>% 
  mutate(id = as.integer(rownames(am_data_tidy))) %>% 
  ggplot(aes(x = id, y = act_counts))+
  geom_line()
```

![](p8105_mtp_hx2263_files/figure-markdown_github/unnamed-chunk-6-1.png)

Using your tidied dataset, aggregate accross minutes to create a total activity variable. Using these data, explore the hypothesis that this participant became more active over time. You may want to want to make comparisons visually and quantitatively.

### Visually

``` r
am_data_tidy %>% 
  group_by(week, day) %>% 
  summarise(total = as.integer(sum(act_counts))) %>% 
  ggplot(aes(y = total, x = seq(1, length(.$total)))) +
  geom_line() +
  geom_smooth()
```

    ## `geom_smooth()` using method = 'loess' and formula 'y ~ x'

![](p8105_mtp_hx2263_files/figure-markdown_github/unnamed-chunk-7-1.png)

### Formal statistical analyses

``` r
week_total = am_data_tidy %>% 
  group_by(week, day) %>% 
  summarise(total = as.integer(sum(act_counts)))
  
(week_total %>% filter(week == 1))$total
```

    ## [1] 196937 432750 297427 369435 366178 416165   1440

``` r
t.test((week_total %>% filter(week == 1))$total, (week_total %>% filter(week == 47))$total, paired=T)
```

    ## 
    ##  Paired t-test
    ## 
    ## data:  (week_total %>% filter(week == 1))$total and (week_total %>% filter(week == 47))$total
    ## t = -1.3034, df = 6, p-value = 0.2402
    ## alternative hypothesis: true difference in means is not equal to 0
    ## 95 percent confidence interval:
    ##  -269746.35   82253.21
    ## sample estimates:
    ## mean of the differences 
    ##               -93746.57

According to the results of two-samples paired test, p-value is 0.2402 larger than significance level 0.05, so we fail to reject the null hypothesis and conclude that there is no significant difference between first week and last week's activity data. So, this participant didn't become more active over time based on formal statistical analyses.

Examine the possibility that day of the week affects activity (in isolation and in addition to the effect of time)

``` r
am_data_tidy %>% 
  group_by(week, day) %>% 
  mutate(dow_total = sum(act_counts)) %>% 
  ggplot(aes(x = week, y = dow_total, color = day)) +
  geom_point(alpha = 0.2, size = .5) +
  geom_smooth()
```

    ## `geom_smooth()` using method = 'gam' and formula 'y ~ s(x, bs = "cs")'

![](p8105_mtp_hx2263_files/figure-markdown_github/unnamed-chunk-9-1.png)

``` r
am_data_tidy %>% 
  group_by(day) %>% 
  summarise(dow_total = sum(act_counts)) %>% 
  ggplot(aes(x = day, y = dow_total)) +
  geom_bar(stat = "identity")
```

![](p8105_mtp_hx2263_files/figure-markdown_github/unnamed-chunk-10-1.png)

第一天

``` r
am_data_tidy %>% 
  filter(week == 1 & day == "Sunday") %>% 
  ggplot(aes(x = time, y = act_counts)) +
  geom_line()
```

![](p8105_mtp_hx2263_files/figure-markdown_github/unnamed-chunk-11-1.png)

Explore the distribution of activity counts in the full dataset, taking into account other variables of interest.

### Make a visualization to show the 24-hour activity “profiles” for each day

### Visualize effect of week on activity in each minute of the 24-hour day

``` r
am_data_tidy %>% 
  group_by(week, time) %>% 
  summarise(sum_act_counts = sum(act_counts)) %>% 
  ggplot(aes(x = time, y = sum_act_counts, color = week)) +
  geom_line(alpha = 0.3) +
  theme_bw() 
```

![](p8105_mtp_hx2263_files/figure-markdown_github/unnamed-chunk-12-1.png)

### day of the week effects on activity in each minute of the 24-hour day

``` r
am_data_tidy %>% 
  group_by(day, time) %>% 
  summarise(sum_act_counts = sum(act_counts)) %>% 
  ggplot(aes(x = time, y = sum_act_counts, color = day)) +
  facet_grid(day ~ ., space = "free") +
  geom_line(alpha = 0.6) +
  theme_bw()
```

![](p8105_mtp_hx2263_files/figure-markdown_github/unnamed-chunk-13-1.png)

incorporating smooth estimates of mean activity profiles may clarify these effects. Comment on relationships you think are interesting.
