---
title: "p8105_mtp_hx2263"
author: "Tiffany Xi"
date: "10/16/2018"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

###Load dataset

Import the data file with `read_csv` using relative path.

```{r df_import, message = FALSE, cache = TRUE}
am_data = 
  read_csv(file = "./data/p8105_mtp_data.csv")
```

###Tidy data

Use `fct_relevel` to reorder the weekdays to normal order and change `day` into factors; Then `gather` takes all `activity.*` columns and collapses into key-value pairs, duplicating all other columns as needed. 

```{r df_tidy}
am_data_tidy = 
  am_data %>% 
  janitor::clean_names() %>% 
  mutate(day = fct_relevel(day, str_c(c("Sunday", "Monday", "Tuesday", "Wednesday",
                                        "Thursday", "Friday", "Saturday"))))%>%
  gather(key = "activity", value = "act_counts", activity_1:activity_1440) %>% 
  separate(activity, into = c("act", "time"), sep = "_") %>% 
  select(-act) %>% 
  arrange(week, day) %>% 
  mutate(time = as.integer(time))
#install.packages("datetime")
#library(datetime)
#as.time(60)
```




